name: Deploy

on:
  push:
    branches:
      - main

env:
    NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build
        env:
            VITE_API_URL_DEBUG: http://localhost:7071
            VITE_API_URL_PROD: https://elecciones-chilea-api-v3.azurewebsites.net
            VITE_API_ENDPOINT_CANDIDATOS: api/EleccionesChileCandidato
            VITE_API_ENDPOINT_PARTIDOS: api/EleccionesChilePartido


      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
